FROM python:3.13
ENV TARGETS=titan:24001

WORKDIR /app

RUN pip install --no-cache-dir --upgrade "fastapi[standard]" aiohttp

COPY main.py /app/.

ENTRYPOINT ["fastapi", "run", "/app/main.py", "--port", "27005"]